root: true

extends:
  - "plugin:@zhzwz/js"
  - "plugin:@zhzwz/ts"
  - "plugin:@zhzwz/vue"
  - "plugin:@zhzwz/json"
  - "plugin:@zhzwz/package.json"
  - "plugin:@zhzwz/tsconfig.json"
  - "plugin:@zhzwz/settings.json"
  - "plugin:@zhzwz/yaml"
  - "plugin:@zhzwz/md"

ignorePatterns:
  - dist
